import { HeroSlide } from "@/types/types";

export const heroSlides: HeroSlide[] = [
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "lg:rtl:items-start",
    justifyEn: "lg:ltr:items-start",
    imgMobilePosition: "bg-center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "Pseudo Harem",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/gijiharem.webp",
    imgMobilePosition: "bg-right",
    justifyEn: "lg:ltr:items-start",
    justifyFa: "lg:rtl:items-end",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "lg:rtl:items-start",
    justifyEn: "lg:ltr:items-start",
    imgMobilePosition: "bg-center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "lg:rtl:items-start",
    justifyEn: "lg:ltr:items-start",
    imgMobilePosition: "bg-center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "lg:rtl:items-start",
    justifyEn: "lg:ltr:items-start",
    imgMobilePosition: "bg-center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "lg:rtl:items-start",
    justifyEn: "lg:ltr:items-start",
    imgMobilePosition: "bg-center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
];
