import { EpisodeCardType, HeroSlide, MediaCardType } from "@/types/types";

export const heroSlides: HeroSlide[] = [
  {
    title: "عنوان انیمه",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/Hero.webp",
    justifyFa: "start",
    justifyEn: "start",
    imgMobilePosition: "center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "Pseudo Harem",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/gijiharem.webp",
    imgMobilePosition: "right",
    justifyEn: "start",
    justifyFa: "end",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
  {
    title: "The Apothecary Diaries",
    desc: "سرنوشت جهان در تعادل است زیرا «ارن» قدرت نهایی تایتان ها را آزاد می‌کند. او با عزم شدیدی برای از بین بردن همه کسانی که الدیا را تهدید می‌کنند، ارتش غیرقابل توقفی از تایتان های عظیم الجثه را به سمت مارلی هدایت می‌کند. حالا یک خدمه متشکل از دوستان و دشمنان سابقش به تقلا می‌افتند تا مأموریت مرگ‌بار او را متوقف کنند، تنها سؤال این است که آیا می‌توانند او را متوقف کنند؟",
    imageUrl: "/images/kusuriya.webp",
    justifyFa: "start",
    justifyEn: "start",
    imgMobilePosition: "center",
    actions: [
      {
        type: "button",
        variant: "default",
        label: "شروع تماشای آنلاین",
        icon: "/svg/play.svg",
        href: "/",
      },
      {
        type: "button",
        variant: "outline",
        label: "افزودن به لیست تماشا",
        icon: "/svg/watchlist.svg",
        href: "/",
        mobileIconOnly: true,
      },
    ],
  },
];

export const recommendations: MediaCardType[] = [
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/onepiece.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
];
export const summerAnime: MediaCardType[] = [
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
  {
    imgUrl: "/images/oshinoko.webp",
    name: "One Piece",
    desc: "زیرنویس چسبیده | پخش آنلاین",
    href: "/",
  },
];

export const userEpisodes: EpisodeCardType[] = [
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "userEpisode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
];

export const newEpisodes: EpisodeCardType[] = [
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
  {
    type: "episode",
    name: "One Piece",
    episode: 9,
    imgUrl: "/images/onepiece.webp",
    href: "/",
    tags: ["زیرنویس چسبیده", "1080p"],
    time: "14:30",
    episodes: 14,
    watched: 9,
    malScore: 8.23,
    aniScore: 79,
  },
];

export const banners = [
  {
    title: "Kaiju",
    logo: "/images/kaijuLogo.png",
    image: "/images/Kaiju.webp",
  },
  {
    title: "Shangri La",
    logo: "/images/shangrilaLogo.png",
    image: "/images/ShangriLa.webp",
  },
];

export const trending = [
  {
    title: "Kusuriya No Hitorigoto",
    image: "/images/Hero.webp",
    tags: "زیرنویس چسبیده | پخش آنلاین",
    description:
      "در دنیایی پر از حیوانات انسان‌نما، «بل لبلانک» تنها کسی بود که به شکل یک انسان عادی به‌دنیا آمده است. بدون داشتن دندان‌های تیز، خز و پولک، به اون لقب بی‌هویت را داده بودند و اون زندگی سخت و پر از تنهایی را سپری می‌کرد و کسی قادر به همدردی با او نبود...",
  },
  {
    title: "Psuedo Harem",
    image: "/images/gijiharem.webp",
    tags: "زیرنویس چسبیده | پخش آنلاین",
    description:
      "در دنیایی پر از حیوانات انسان‌نما، «بل لبلانک» تنها کسی بود که به شکل یک انسان عادی به‌دنیا آمده است. بدون داشتن دندان‌های تیز، خز و پولک، به اون لقب بی‌هویت را داده بودند و اون زندگی سخت و پر از تنهایی را سپری می‌کرد و کسی قادر به همدردی با او نبود...",
  },
];
