import type { Metadata } from "next";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const modam = localFont({
  src: [
    {
      path: "../../public/fonts/modamWeb-extraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-extraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/modamWeb-black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <>
      <html
        lang={locale}
        dir={locale === "fa" ? "rtl" : "ltr"}
        suppressHydrationWarning
      >
        <head />
        <body className={`dark:bg-background ${modam.className}`}>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </>
  );
}
